### ISSUE TITLE
No usar números para la lista de empresas Nearshore

### ISSUE THREAD

**Issue by cesc1989** [suarezafelipe/awesome-jobs-colombia#11]
Creo que eso hace que se enrede un poco a la hora de aceptar los PR ya que algunos podrían ingresar varias veces el item número "7", por ejemplo.

Usando viñetas normales sería más sencillo, en mí opinión. :v:

**Comment by suarezafelipe** [comment]
Fixed in afd6f48f7d65a23c23c4ae8c9c84fde35187715f

**Comment by cesc1989** [comment]
Incluso mejor @suarezafelipe 😄 ! 👍
