### ISSUE TITLE
Agregar Categoría "Red Flag"

### ISSUE THREAD

**Issue by sagrath23** [suarezafelipe/awesome-jobs-colombia#12]
Sería de gran ayuda tener una categoría donde se agrupen las empresas _a evitar_ en procesos de reclutamiento. Y que a partir de issues reportados por la comunidad, se puedan mover/quitar de esta categoría.

**Comment by suarezafelipe** [comment]
Me parece un poco dificil ser objetivo con eso, preferiría sección de "comentarios" donde se pongan experiencias buenas y malas y ya que cada quién tome sus propias decisiones, @sagrath23 qué opinas?

**Comment by Addin** [comment]
Concuerdo, sería algo extremo indicar que hay que evitar una empresa solo porque algunas personas tuvieron malas experiencias, lo de comentar las experiencias buenas y malas sería algo tipo Glassdoor, ¿no? es probable que eso desvirtúe el propósito de este repositorio, también entiendo que el repositorio es público y si hay un consenso, no veo problema en añadir esa sección
si eso beneficia a la comunidad.

**Comment by cesc1989** [comment]
Creo que se podría usar el Wiki del repositorio para este propósito de lista de _red flags_.

**Comment by sagrath23** [comment]
La idea de usar el Wiki de GitHub me parece muy buena...

**Comment by suarezafelipe** [comment]
Con los wikis se puede tener el mismo flow de PR + review + merge ?

**Comment by cesc1989** [comment]
@suarezafelipe No, en los wikis creo que no hay ese flujo PERO creo que se puede limitar quiénes aportan.

**Comment by suarezafelipe** [comment]
Acabo de modificar los settings del repo, creo que ya es posible para todos modificar la wiki

@cesc1989 puedes probar porfa?

**Comment by cesc1989** [comment]
Listo, ya deja que la modifique @suarezafelipe 👍

**Comment by juandav** [comment]
Podríamos crear entre la comunidad una app, que permita hacer esto un poco mas fluido, no se es mi idea. Ejemplo: Lista de empresas como un card con imagen representativa y que al dar click se despliegue sintetizado de los lenguajes que trabaja la empresa, comentarios positivos y negativos, etc. algo así como para iniciar, les parece buena idea, es excesivo?

**Comment by juandav** [comment]
Una especie de calificación, pais del que es la empresa, niveles(junior, mid, senior) etc....

**Comment by suarezafelipe** [comment]
@juandav tengo un side project, que aunque no es una app, si podría ser una web app responsive o dejar el json abierto para el que quiera hacer una app

@sagrath23 @cesc1989 @Addin ya quedo la wiki abierta y lista para que puedan postear comentarios de las empresas https://github.com/suarezafelipe/awesome-jobs-colombia/wiki
