### ISSUE TITLE
Terminar las categorizaciones

### ISSUE THREAD

**Issue by suarezafelipe** [suarezafelipe/awesome-jobs-colombia#34]
Con la creación de la Wiki para reviews de empresas, lo único que falta para "terminar" este repo es quitar la sección de "Por Categorizar"

Alguien podría tomarse el tiempo de entrar a la pág/googlear cada una de las empresas que quedaron por categorizar y ponerla en donde corresponda?

@Addin @cesc1989 de pronto? 😃

**Comment by Addin** [comment]
Sí señor, me puedo encargar de eso.

**Comment by cesc1989** [comment]
Dale pues. Vamos a ver qué se encuentra. Ahí mandé el 1er PR 😄

**Comment by cesc1989** [comment]
Tata e Indra parecen ser un híbrido. Nearshore con productos propios:

Tata en el pie de página tiene Servicio (consultoria) y Productos.

Indra dice:

> Indra es una de las principales compañías globales de tecnología y **consultoría** y el socio tecnológico para las operaciones clave de los negocios de sus clientes en todo el mundo. Es un proveedor líder mundial de soluciones propias en segmentos específicos de los mercados de Transporte y Defensa, y la empresa **líder en consultoría de transformación digital** y Tecnologías de la Información en España y Latinoamérica a través de su filial Minsait. Su modelo de negocio está basado en una **oferta integral de productos propios**

¿Cómo proceder ahí?

**Comment by suarezafelipe** [comment]
ambas (sobretodo Tata) las conozco como las "globant" de india

si tienen prods propios no serán tan conocidos como sus servicios de consultoria, así que pongamolas en nearshore/outsourcing

(no las puse ahí en un principio es porque no sabía si había puestos para **devs** principalmente)

**Comment by Addin** [comment]
Espero no haber roto demasiadas cosas, parece que esto ya quedo solucionado.

@suarezafelipe si tienes tiempo por favor me puedes enseñar a arreglar los merge conflicts y a enviar los PR desde un branch diferente (quiero que cada commit sea un PR diferente).
