### ISSUE TITLE
Añadir los enlaces a la página de careers de cada empresa

### ISSUE THREAD

**Issue by Addin** [suarezafelipe/awesome-jobs-colombia#4]
Para ahorrar tiempo, una sugerencia sería añadir el enlace directo a la página de careers de cada empresa.

**Comment by suarezafelipe** [comment]
De acuerdo! Ya se hizo con la empresa Instaleap.io por ejemplo

Agradecería PRs al respecto 🙏

**Comment by suarezafelipe** [comment]
Solved with: https://github.com/suarezafelipe/awesome-jobs-colombia/pull/5
