### ISSUE TITLE
Añadir las siguientes empresas

### ISSUE THREAD

**Issue by carlochess** [suarezafelipe/awesome-jobs-colombia#7]
(Yo puedo hacer el pull request pero quiero discutir si vale la pena añadir las siguientes empresas)

Producto propio
[Twilio](https://www.twilio.com/company) (Bogota)
[Truora](https://www.truora.com/) (Cali)
[Merlin](https://merlinjobs.com/) (Bogota)
[Blackboard](https://ush.blackboard.com/) (Bogota)
[Muy](https://home.muy.com.co/#/) (Bogota)
[Aval digitalabs](https://www.linkedin.com/company/avaldigitallabs/) (Bogota)
[Scotiabank](https://www.scotiabankcolpatria.com/) (Bogota)
[Lendingfront](https://lendingfront.com/) (Remote)
[Zinobe](https://www.zinobe.com/inicio) (Bogota)
[Addi](https://www.addi.com/) (Bogota)

**Comment by Addin** [comment]
No debería haber problema en agregarlas, con tal de que cumplan la condición de que tengan una página de careers y el trabajo sea en desarrollo de software :+1:

**Comment by suarezafelipe** [comment]
@carlochess adelante con el PR; eso si ten en cuenta poner las que son en español (ej Aval digitallabs, supongo que Scotiabank también) en la parte de "Español" y no en producto propio

**Comment by suarezafelipe** [comment]
Done in https://github.com/suarezafelipe/awesome-jobs-colombia/pull/9
